"""Schemas package."""

from app.schemas.auth import (
    # Auth
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    TokenResponse,
    PasswordChangeRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
    PasswordResetConfirmResponse,
    PasswordResetVerifyRequest,

    # MFA
    MFASetupResponse,
    MFAVerifyRequest,
    MFADisableRequest,
    # Usuario
    UsuarioBase,
    UsuarioCreate,
    UsuarioUpdate,
    UsuarioSelfUpdate,
    UsuarioRead,
    UsuarioReadOperacional,
    UsuarioReadGestor,
    UsuarioReadAuditor,
    UsuarioMinimal,
    UsuarioMinimalColaborador,
    EquipeMembroMinimal,
    # Tenant
    TenantBase,
    TenantCreate,
    TenantUpdate,
    TenantRead,
    # Register (SaaS)
    RegisterTenantRequest,
    RegisterTenantResponse,
    # Equipe
    EquipeBase,
    EquipeCreate,
    EquipeUpdate,
    EquipeRead,
    EquipeWithMembers,
)
from app.schemas.base import (
    BaseSchema,
    TimestampSchema,
    PaginationParams,
    PaginatedResponse,
    ErrorResponse,
    SuccessResponse,
    DateRangeFilter,
    SearchFilter,
    GeoPoint,
    GeoPolygon,
)
from app.schemas.beneficios import (
    CarteiraBase,
    CarteiraCreate,
    CarteiraUpdate,
    CarteiraRead,
    CarteiraWithCards,
    CarteiraSaldo,
    CartaoBase,
    CartaoCreate,
    CartaoRead,
    CartaoBloqueio,
    RecargaBase,
    RecargaCreate,
    RecargaLote,
    RecargaRead,
    RecargaLoteStatus,
    TransacaoBase,
    TransacaoRead,
    TransacaoFilter,
    ExtratoResponse,
    PoliticaBeneficio,
)
from app.schemas.documentos import (
    DocumentoBase,
    DocumentoCreate,
    DocumentoUpload,
    DocumentoUpdate,
    DocumentoRead,
    DocumentoWithAssinaturas,
    AssinaturaRequest,
    AssinaturaRead,
    AssinaturaVerify,
    LoteDocumentosCreate,
    LoteDocumentosUpload,
    LoteDocumentosStatus,
    HoleriteImport,
    HoleriteRead,
)
from app.schemas.geo import (
    PerimetroBase,
    PerimetroCreateCircle,
    PerimetroCreatePolygon,
    PerimetroUpdate,
    PerimetroRead,
    PerimetroValidateRequest,
    PerimetroValidateResponse,
    JanelaHorario,
    EscalaBase,
    EscalaCreate,
    EscalaUpdate,
    EscalaRead,
    DispositivoBase,
    DispositivoRegister,
    DispositivoUpdate,
    DispositivoRead,
    DispositivoAttestation,
)
from app.schemas.ponto import (
    MarcacaoBase,
    MarcacaoCreate,
    MarcacaoOfflineSync,
    MarcacaoUpdate,
    MarcacaoRead,
    MarcacaoWithAuditoria,
    AuditoriaRead,
    AuditoriaRevisao,
    Comprovante,
    EspelhoDia,
    EspelhoPonto,
    EspelhoFilter,
    AEJExportRequest,
    AEJExportResponse,
    CorrecaoRequest,
    CorrecaoAprovacao,
    CorrecaoRead,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "SuccessResponse",
    "DateRangeFilter",
    "SearchFilter",
    "GeoPoint",
    "GeoPolygon",
    # Auth
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "TokenResponse",
    "PasswordChangeRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    "PasswordResetConfirmResponse",
    "MFASetupResponse",
    "MFAVerifyRequest",
    "MFADisableRequest",
    # Usuario
    "UsuarioBase",
    "UsuarioCreate",
    "UsuarioUpdate",
    "UsuarioSelfUpdate",
    "UsuarioRead",
    "UsuarioReadGestor",
    "UsuarioReadAuditor",
    "UsuarioMinimal",
    "UsuarioMinimalColaborador",
    # Tenant
    "TenantBase",
    "TenantCreate",
    "TenantUpdate",
    "TenantRead",
    # Equipe
    "EquipeBase",
    "EquipeCreate",
    "EquipeUpdate",
    "EquipeRead",
    "EquipeWithMembers",
    # Ponto
    "MarcacaoBase",
    "MarcacaoCreate",
    "MarcacaoOfflineSync",
    "MarcacaoUpdate",
    "MarcacaoRead",
    "MarcacaoWithAuditoria",
    "AuditoriaRead",
    "AuditoriaRevisao",
    "Comprovante",
    "EspelhoDia",
    "EspelhoPonto",
    "EspelhoFilter",
    "AEJExportRequest",
    "AEJExportResponse",
    "CorrecaoRequest",
    "CorrecaoAprovacao",
    "CorrecaoRead",
    # Geo
    "PerimetroBase",
    "PerimetroCreateCircle",
    "PerimetroCreatePolygon",
    "PerimetroUpdate",
    "PerimetroRead",
    "PerimetroValidateRequest",
    "PerimetroValidateResponse",
    "JanelaHorario",
    "EscalaBase",
    "EscalaCreate",
    "EscalaUpdate",
    "EscalaRead",
    "DispositivoBase",
    "DispositivoRegister",
    "DispositivoUpdate",
    "DispositivoRead",
    "DispositivoAttestation",
    # Documentos
    "DocumentoBase",
    "DocumentoCreate",
    "DocumentoUpload",
    "DocumentoUpdate",
    "DocumentoRead",
    "DocumentoWithAssinaturas",
    "AssinaturaRequest",
    "AssinaturaRead",
    "AssinaturaVerify",
    "LoteDocumentosCreate",
    "LoteDocumentosUpload",
    "LoteDocumentosStatus",
    "HoleriteImport",
    "HoleriteRead",
    # Beneficios
    "CarteiraBase",
    "CarteiraCreate",
    "CarteiraUpdate",
    "CarteiraRead",
    "CarteiraWithCards",
    "CarteiraSaldo",
    "CartaoBase",
    "CartaoCreate",
    "CartaoRead",
    "CartaoBloqueio",
    "RecargaBase",
    "RecargaCreate",
    "RecargaLote",
    "RecargaRead",
    "RecargaLoteStatus",
    "TransacaoBase",
    "TransacaoRead",
    "TransacaoFilter",
    "ExtratoResponse",
    "PoliticaBeneficio",
]
